name: Build and Release .NET Console App

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout your repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # Restore NuGet packages
      - name: Restore dependencies
        run: dotnet restore

      # Build the project
      - name: Build project
        run: dotnet build --configuration Release --no-restore

      # Publish the console app
      - name: Publish project
        run: dotnet publish TrackerUI/TrackerUI.csproj -c Release -r win-x64 -o publish --self-contained true

      # Check the output
      - name: List published files
        run: ls -R publish/

      # Zip the published output
      - name: Zip published files
        run: zip -r release.zip publish/

      # Create GitHub Release and upload asset
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
